### ISSUE TITLE
nothing over 12 hours works 

### ISSUE THREAD

**Issue by Jusatoker** [emanueltilly/Timecode-for-Companion#2]
Anytime my timecode comming into program is over the 13:00:00 it plays 3:00:00

**Comment by emanueltilly** [comment]
What source of timecode are you using?
Have you tried different sources of timecode?

Please provide more details about your environment if possible.

**Comment by Jusatoker** [comment]
My timecode source comes from our playback rig at 29.97 nd 
it then goes into destriplizer outputed to mif4 into program 
i have tried from different sources to no luck

**Comment by Jusatoker** [comment]
It is being generated from tracks rig. Going into a destriplizer for distribution. Then hitting a mif4 to get into program. I am running 29.97 nd time code 

Thanks,
Ricky Krohne 
+1(615)349-0866

**Comment by emanueltilly** [comment]
While 29.97 fps is not a supported framerate (see FPS drop-down menu), I don't see how that would cause this issue. 

For troubleshooting purposes it would be helpful if you could:

- See if the problem persists running a supported FPS into the software 
- Record the LTC Timecode at 3h and 13h and upload for me to recreate the issue
- See if the problem persists with the MIF4s internally generated timecode

**Comment by emanueltilly** [comment]
Release 1.1.0.0 includes a bugfix regarding a issue where 16 hours would wrap around to 0 hours.
Please try this release on your setup and see if it solves the problem.
