### ISSUE TITLE
not receiving udp packets

### ISSUE THREAD

**Issue by ervings** [emanueltilly/Timecode-for-Companion#4]
Hi!
Great software, I really want to make it work in my production line, but somehow I fail to receive any packets.
Is there a specific non-standart way to input port for the app?
I am setting a companion IP like this- 127.0.0.1:16759
but I don't receive any cues (udp on companion is on, tested with packet sender, all works)
maybe there is some problem with my system and app installation? I am on windows11, turned off the firewall, but no luck.
Any tips appreciated
(I see in your app screenshot that there is no port set in your example - which is the default port the app uses?)

Ervings

**Comment by emanueltilly** [comment]
Hi,
It's sending on port 51235, which should be the port Companion is listening for by default.

Are you trying to send UDP packets from Companion to this software?

**Comment by ervings** [comment]
thank you so much - it works on the port you mentioned!!!

(companion had different port set by default in my installation - that means it is not possible to pass port by addiing it to ip.
Is there a way to specify port in the saved project xml?

**Comment by emanueltilly** [comment]
That is correct, you cannot specify a port in the IP address string.
The port is currently hardcoded since, at the time of latest release, Companion Remote ports could not be changed.
I will add this feature, but can't give a time estimate.
