### ISSUE TITLE
Idea for cleaner view

### ISSUE THREAD

**Issue by ervings** [emanueltilly/Timecode-for-Companion#5]
Hi, thanks for clarifying the port issue.

If you are doing some updates, could it be possible to add a feature of displaying different page assignments as separate tabs? It would greatly improve the overview if I use a large ammount of different cues in show.

**Comment by emanueltilly** [comment]
Thank you for your suggestion. While incorporating this feature would require making significant changes to the app, I agree that it would be helpful to visually differentiate rows without relying solely on reading. As a result, I have added a feature that allows users to set a preferred background color for each row. I hope this enhancement improves the overall user experience and makes it easier to use the app.
